[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/ruma/ruma.git"]
git = "https://github.com/ruma/ruma.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
